
services:
  home:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5050:3000
    networks:
      - frontend-networks
networks:
  frontend-networks:
    external: true
